### PR TITLE
Create Astro template

### PR DESCRIPTION
**Pull request by AlgorithmEnigma**
Astro is a popular framework, I made this so I can use bun to create the template

### CODE REVIEW

**Comment by xHyroM** [comment]
Does Astro use bun runtime (like if you use `bun run dev`)

**Comment by AlgorithmEnigma** [comment]
Astro can use bun, see https://docs.astro.build/en/recipes/bun/

**Comment by xHyroM** [comment]
You need to wait for @Jarred-Sumner or @SaltyAom because i don't have access to merge this, sorry :(

**Review by SaltyAom — APPROVED** [review]

**Comment by SaltyAom** [comment]
Didn't know Astro could run on Bun.

Alright, this looks good to me, let's get this merge.

**Pull request merged**
